package employeeSystem.com.website.system.model;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 2019/2/13 �U�� 12:21:10 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbAnnounceDoc generated by hbm2java
 */
@Entity
@Table(name = "tb_announce_doc", catalog = "yesee")
public class TbAnnounceDoc implements java.io.Serializable {

	private int docId;
	private String announceId;
	private String name;
	private String docPath;

	public TbAnnounceDoc() {
	}

	public TbAnnounceDoc(int docId, String announceId, String name, String docPath) {
		this.docId = docId;
		this.announceId = announceId;
		this.name = name;
		this.docPath = docPath;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "doc_id", unique = true, nullable = false)
	public int getDocId() {
		return this.docId;
	}

	public void setDocId(int docId) {
		this.docId = docId;
	}

	@Column(name = "announce_id", nullable = false, length = 20)
	public String getAnnounceId() {
		return this.announceId;
	}

	public void setAnnounceId(String announceId) {
		this.announceId = announceId;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "doc_path", nullable = false, length = 200)
	public String getDocPath() {
		return this.docPath;
	}

	public void setDocPath(String docPath) {
		this.docPath = docPath;
	}

}
