package com.yesee.gov.website.model;
//default package

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbEmployees generated by hbm2java
 */
@Embeddable
public class TbAnnualLeaveId implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -805145754759654473L;
	private String empName;
	private String year;

	public TbAnnualLeaveId() {
		super();
	}

	public TbAnnualLeaveId(String empName, String year) {
		super();
		this.empName = empName;
		this.year = year;
	}

	@Column(name = "emp_name", unique = true, nullable = false, length = 100)
	public String getEmpName() {
		return empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	@Column(name = "year", nullable = false, length = 256)
	public String getYear() {
		return year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((empName == null) ? 0 : empName.hashCode());
		result = prime * result + ((year == null) ? 0 : year.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TbAnnualLeaveId other = (TbAnnualLeaveId) obj;
		if (empName == null) {
			if (other.empName != null)
				return false;
		} else if (!empName.equals(other.empName))
			return false;
		if (year == null) {
			if (other.year != null)
				return false;
		} else if (!year.equals(other.year))
			return false;
		return true;
	}

}
