package com.yesee.gov.website.model;
// default package

// Generated 2019/1/18 �W�� 10:49:25 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbAnnounce generated by hbm2java
 */
@Entity
@Table(name = "tb_announce", catalog = "yesee")
public class TbAnnounce implements java.io.Serializable {

	private Integer id;
	private String companyId;
	private String subject;
	private String content;
	private Date createdAt;
	private String createUser;
	private Date updatedAt;
	private String updateUser;
	private String type;

	public TbAnnounce() {
	}

	public TbAnnounce(String subject, String content, Date createdAt, String createUser, String type) {
		this.subject = subject;
		this.content = content;
		this.createdAt = createdAt;
		this.createUser = createUser;
		this.type = type;
	}

	public TbAnnounce(String companyId, String subject, String content, Date createdAt, String createUser,
			Date updatedAt, String updateUser, String type) {
		this.companyId = companyId;
		this.subject = subject;
		this.content = content;
		this.createdAt = createdAt;
		this.createUser = createUser;
		this.updatedAt = updatedAt;
		this.updateUser = updateUser;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "company_id", length = 45)
	public String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	@Column(name = "subject", nullable = false, length = 45)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "create_user", nullable = false, length = 45)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "update_user", length = 45)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Column(name = "type", length = 1, nullable = false)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
