package com.yesee.gov.website.model;
//default package
//Generated 2018/7/19 �U�� 03:30:01 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
* TbGroupFunction generated by hbm2java
*/
@Entity
@Table(name = "tb_annual_leave", catalog = "yesee")
public class TbAnnualLeave implements java.io.Serializable {

	private TbAnnualLeaveId id;
	private TbEmployees tbEmployees;
	private String entitledHours;
	private String availableHours;
	private String makeupHours;

	public TbAnnualLeave() {
	}

	public TbAnnualLeave(TbAnnualLeaveId id, TbEmployees tbEmployees) {
		this.id = id;
		this.tbEmployees = tbEmployees;
	}

	public TbAnnualLeave(TbAnnualLeaveId id, TbEmployees tbEmployees, String entitledHours, String availableHours,
			String makeupHours) {
		this.id = id;
		this.tbEmployees = tbEmployees;
		this.entitledHours = entitledHours;
		this.availableHours = availableHours;
		this.makeupHours = makeupHours;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "empName", column = @Column(name = "emp_name", nullable = false, length = 100)),
			@AttributeOverride(name = "year", column = @Column(name = "year", nullable = false, length = 256)) })
	public TbAnnualLeaveId getId() {
		return this.id;
	}

	public void setId(TbAnnualLeaveId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "emp_name", nullable = false, insertable = false, updatable = false)
	public TbEmployees getTbEmployees() {
		return this.tbEmployees;
	}

	public void setTbEmployees(TbEmployees tbEmployees) {
		this.tbEmployees = tbEmployees;
	}

	@Column(name = "entitled_hours", length = 256)
	public String getEntitledHours() {
		return this.entitledHours;
	}

	public void setEntitledHours(String entitledHours) {
		this.entitledHours = entitledHours;
	}

	@Column(name = "available_hours", length = 256)
	public String getAvailableHours() {
		return this.availableHours;
	}

	public void setAvailableHours(String availableHours) {
		this.availableHours = availableHours;
	}

	@Column(name = "makeup_hours", length = 256)
	public String getMakeupHours() {
		return this.makeupHours;
	}

	public void setMakeupHours(String makeupHours) {
		this.makeupHours = makeupHours;
	}

}
