package com.yesee.gov.website.model;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.yesee.gov.website.model.accounting.TbAClassItem;

/**
 * TbPunchRecords generated by hbm2java
 */
@Entity
@Table(name = "tb_company", catalog = "yesee")
public class TbCompany implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	@Column(name = "name",unique = true, nullable = false, length = 45)
	private String name;

	public TbCompany() {
	}
	
	

	public TbCompany(String name) {
		
		this.name = name;
	}



	public TbCompany(Integer id, String name) {
		this.id = id;
		this.name = name;
	}


	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
//	@OneToMany(fetch = FetchType.LAZY)
//	@JoinColumn(name = "name")
//	private List<TbCompany> nameList;

}
