package com.yesee.gov.website.model;
// default package
// Generated 2019/3/27 �U�� 02:38:03 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbDeleteCode generated by hbm2java
 */
@Entity
@Table(name = "tb_delete_code", catalog = "yesee")
public class TbDeleteCode implements java.io.Serializable {

	private long id;
	private String hashcode;
	private String signer;
	private int scheduleId;

	public TbDeleteCode() {
	}

	public TbDeleteCode(long id, String hashcode, String signer, int scheduleId) {
		this.id = id;
		this.hashcode = hashcode;
		this.signer = signer;
		this.scheduleId = scheduleId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "hashcode", nullable = false, length = 200)
	public String getHashcode() {
		return this.hashcode;
	}

	public void setHashcode(String hashcode) {
		this.hashcode = hashcode;
	}

	@Column(name = "signer", nullable = false, length = 45)
	public String getSigner() {
		return this.signer;
	}

	public void setSigner(String signer) {
		this.signer = signer;
	}

	@Column(name = "schedule_id", nullable = false)
	public int getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(int scheduleId) {
		this.scheduleId = scheduleId;
	}

}
