package employeeSystem.com.website.system.model;
//default package

//Generated 2018/7/19 �U�� 03:30:01 by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbEmployees generated by hbm2java
 */
@Entity
@Table(name = "tb_employees", catalog = "yesee")
public class TbEmployees implements java.io.Serializable {

	private String username;
	private String chineseName;
	private String groupId;
	private String status;
	private Date onBoardDate;
	private Date createdAt;
	private Date updatedAt;
	private String departmentId;

	public TbEmployees() {
	}

	public TbEmployees(String username, String groupId, String status) {
		this.username = username;
		this.groupId = groupId;
		this.status = status;
	}

	public TbEmployees(String username, String groupId, String status, Date createdAt, Date updatedAt) {
		this.username = username;
		this.groupId = groupId;
		this.status = status;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@Column(name = "username", unique = true, nullable = false, length = 25)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "group_id", nullable = false, length = 10)
	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "department_id", length = 10)
	public String getDepartmentId() {
		return departmentId;
	}

	public void setDepartmentId(String departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "chinese_name", nullable = true, length = 100)
	public String getChineseName() {
		return chineseName;
	}

	public void setChineseName(String chineseName) {
		this.chineseName = chineseName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "on_board_date", length = 19)
	public Date getOnBoardDate() {
		return onBoardDate;
	}

	public void setOnBoardDate(Date onBoardDate) {
		this.onBoardDate = onBoardDate;
	}

}
