package com.yesee.gov.website.model;

//default package
//Generated 2018/7/19 �U�� 03:30:01 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
* TbFunction generated by hbm2java
*/
@Entity
@Table(name = "tb_function", catalog = "yesee")
public class TbFunction implements java.io.Serializable {

	private String id;
	private String parentId;
	private String name;
	private String url;
	private int sort;

	public TbFunction() {
	}

	public TbFunction(String id, String name, String url, int sort) {
		this.id = id;
		this.name = name;
		this.url = url;
		this.sort = sort;
	}

	public TbFunction(String id, String parentId, String name, String url, int sort) {
		this.id = id;
		this.parentId = parentId;
		this.name = name;
		this.url = url;
		this.sort = sort;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 10)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "parent_id", length = 10)
	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "url", nullable = false, length = 256)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "sort", nullable = false)
	public int getSort() {
		return this.sort;
	}

	public void setSort(int sort) {
		this.sort = sort;
	}

}
