package com.yesee.gov.website.model;
//default package
//Generated 2018/7/19 �U�� 03:30:01 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;


/**
* TbGroupFunctionId generated by hbm2java
*/
@Embeddable
public class TbGroupFunctionId implements java.io.Serializable {

	private String groupId;
	private String funcId;

	public TbGroupFunctionId() {
	}

	public TbGroupFunctionId(String groupId, String funcId) {
		this.groupId = groupId;
		this.funcId = funcId;
	}

	@Column(name = "group_id", nullable = false, length = 10)
	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	@Column(name = "func_id", nullable = false, length = 10)
	public String getFuncId() {
		return this.funcId;
	}

	public void setFuncId(String funcId) {
		this.funcId = funcId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbGroupFunctionId))
			return false;
		TbGroupFunctionId castOther = (TbGroupFunctionId) other;

		return ((this.getGroupId() == castOther.getGroupId()) || (this.getGroupId() != null
				&& castOther.getGroupId() != null && this.getGroupId().equals(castOther.getGroupId())))
				&& ((this.getFuncId() == castOther.getFuncId()) || (this.getFuncId() != null
						&& castOther.getFuncId() != null && this.getFuncId().equals(castOther.getFuncId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getGroupId() == null ? 0 : this.getGroupId().hashCode());
		result = 37 * result + (getFuncId() == null ? 0 : this.getFuncId().hashCode());
		return result;
	}

}
