package com.yesee.gov.website.model;
//default package

//Generated 2018/7/19 �U�� 03:30:01 by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbGroup generated by hbm2java
 */
@Entity
@Table(name = "tb_holiday_event", catalog = "yesee")
public class TbHolidayEvent implements java.io.Serializable {

	private Integer id;
	private String holidayName;
	private Integer holidayType;
	private Date startDate;
	private Date endDate;

	public TbHolidayEvent() {
	}

	public TbHolidayEvent(Integer id, String holidayName, Integer holidayType, Date startDate, Date endDate) {
		super();
		this.id = id;
		this.holidayName = holidayName;
		this.holidayType = holidayType;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Id

	@GeneratedValue(strategy = javax.persistence.GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "holiday_name", nullable = true, length = 100)
	public String getHolidayName() {
		return holidayName;
	}

	public void setHolidayName(String holidayName) {
		this.holidayName = holidayName;
	}

	@Column(name = "holiday_type", nullable = false)
	public Integer getHolidayType() {
		return holidayType;
	}

	public void setHolidayType(Integer holidayType) {
		this.holidayType = holidayType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", length = 19)
	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date", length = 19)
	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
