package employeeSystem.com.website.system.model;
// default package

// Generated 2019/1/23 �U�� 02:23:28 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbProject generated by hbm2java
 */
@Entity
@Table(name = "tb_project", catalog = "yesee")
public class TbProject implements java.io.Serializable {

	private Integer id;
	private TbEmployees pm;
	private String name;
	private int type;
	private int siId;
	private Integer endUserId;
	private String devStatus;
	private Date startTime;
	private Date updatedAt;

	public TbProject() {
	}

	public TbProject(TbEmployees tbEmployees, String name, int type, int siId, String devStatus) {
		this.pm = tbEmployees;
		this.name = name;
		this.type = type;
		this.siId = siId;
		this.devStatus = devStatus;
	}

	public TbProject(TbEmployees tbEmployees, String name, int type, int siId, Integer endUserId, String devStatus,
			Date startTime, Date updatedAt) {
		this.pm = tbEmployees;
		this.name = name;
		this.type = type;
		this.siId = siId;
		this.endUserId = endUserId;
		this.devStatus = devStatus;
		this.startTime = startTime;
		this.updatedAt = updatedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pm", nullable = false)
	public TbEmployees getPM() {
		return this.pm;
	}

	public void setPM(TbEmployees tbEmployees) {
		this.pm = tbEmployees;
	}

	@Column(name = "name", nullable = false, length = 256)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "si_id", nullable = false)
	public int getSiId() {
		return this.siId;
	}

	public void setSiId(int siId) {
		this.siId = siId;
	}

	@Column(name = "end_user_id")
	public Integer getEndUserId() {
		return this.endUserId;
	}

	public void setEndUserId(Integer endUserId) {
		this.endUserId = endUserId;
	}

	@Column(name = "dev_status", nullable = false, length = 20)
	public String getDevStatus() {
		return this.devStatus;
	}

	public void setDevStatus(String devStatus) {
		this.devStatus = devStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_time", length = 19)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}
