package com.yesee.gov.website.model;
//default package

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbGroup generated by hbm2java
 */
@Entity
@Table(name = "tb_project_assist", catalog = "yesee")
public class TbProjectAssist implements java.io.Serializable {

	private int id;
	private int projectId;
	private int depId;

	public TbProjectAssist() {
	}

	public TbProjectAssist(int id, int projectId, int depId) {
		super();
		this.id = id;
		this.projectId = projectId;
		this.depId = depId;
	}

	@Id

	@GeneratedValue(strategy = javax.persistence.GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "project_id")
	public int getProjectId() {
		return projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "dep_id")
	public int getDepId() {
		return depId;
	}

	public void setDepId(int depId) {
		this.depId = depId;
	}

}
