package com.yesee.gov.website.model;
// default package
// Generated 2019/2/26 �W�� 09:21:59 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbProjectMember generated by hbm2java
 */
@Entity
@Table(name = "tb_project_member", catalog = "yesee")
public class TbProjectMember implements java.io.Serializable {

	private int id;
	private TbEmployees tbEmployees;
	private TbProject tbProject;
	private Date createdAt;

	public TbProjectMember() {
	}

	public TbProjectMember(int id, TbEmployees tbEmployees, TbProject tbProject, Date createdAt) {
		this.id = id;
		this.tbEmployees = tbEmployees;
		this.tbProject = tbProject;
		this.createdAt = createdAt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user", nullable = false)
	public TbEmployees getTbEmployees() {
		return this.tbEmployees;
	}

	public void setTbEmployees(TbEmployees tbEmployees) {
		this.tbEmployees = tbEmployees;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "project_id", nullable = false)
	public TbProject getTbProject() {
		return this.tbProject;
	}

	public void setTbProject(TbProject tbProject) {
		this.tbProject = tbProject;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
