package com.yesee.gov.website.model;
//default package

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbGroup generated by hbm2java
 */
@Entity
@Table(name = "tb_project_type", catalog = "yesee")
public class TbProjectType implements java.io.Serializable {

	private int id;
	private String name;
	private int ownDep;

	public TbProjectType() {
	}

	public TbProjectType(int id, String name, int ownDep) {
		super();
		this.id = id;
		this.name = name;
		this.ownDep = ownDep;
	}

	@Id

	@GeneratedValue(strategy = javax.persistence.GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 256)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "own_dep")
	public int getOwnDep() {
		return ownDep;
	}

	public void setOwnDep(int ownDep) {
		this.ownDep = ownDep;
	}

}
