package employeeSystem.com.website.system.model;
// default package

// Generated 2019/1/8 �U�� 03:10:49 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbPreferenceId generated by hbm2java
 */
@Embeddable
public class TbPreferenceId implements java.io.Serializable {

	private String username;
	private String configKey;

	public TbPreferenceId() {
	}

	public TbPreferenceId(String username, String configKey) {
		this.username = username;
		this.configKey = configKey;
	}

	@Column(name = "username", nullable = false, length = 100)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "config_key", nullable = false, length = 45)
	public String getConfigKey() {
		return this.configKey;
	}

	public void setConfigKey(String configKey) {
		this.configKey = configKey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbPreferenceId))
			return false;
		TbPreferenceId castOther = (TbPreferenceId) other;

		return ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
				&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())))
				&& ((this.getConfigKey() == castOther.getConfigKey()) || (this.getConfigKey() != null
						&& castOther.getConfigKey() != null && this.getConfigKey().equals(castOther.getConfigKey())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result + (getConfigKey() == null ? 0 : this.getConfigKey().hashCode());
		return result;
	}

}
