package employeeSystem.com.website.system.model;
// default package

// Generated 2019/1/8 �U�� 03:10:49 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TbPreference generated by hbm2java
 */
@Entity
@Table(name = "tb_preference", catalog = "yesee")
public class TbPreference implements java.io.Serializable {

	private TbPreferenceId id;
	private String value;

	public TbPreference() {
	}

	public TbPreference(TbPreferenceId id, String value) {
		this.id = id;
		this.value = value;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "username", column = @Column(name = "username", nullable = false, length = 100)),
			@AttributeOverride(name = "configKey", column = @Column(name = "config_key", nullable = false, length = 45)) })
	public TbPreferenceId getId() {
		return this.id;
	}

	public void setId(TbPreferenceId id) {
		this.id = id;
	}

	@Column(name = "value", nullable = false, length = 200)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
