package com.yesee.gov.website.model;
// default package
// Generated 2019/4/10 �W�� 11:33:19 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbProjectItemSort generated by hbm2java
 */
@Entity
@Table(name = "tb_project_item_sort", catalog = "yesee")
public class TbProjectItemSort implements java.io.Serializable {

	private Integer id;
	private String name;

	public TbProjectItemSort() {
	}

	public TbProjectItemSort(String name) {
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
