package com.yesee.gov.website.model;
// default package
// Generated 2019/4/11 �W�� 11:08:57 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * TbProjectItem generated by hbm2java
 */
@Entity
@Table(name = "tb_project_item", catalog = "yesee")
public class TbProjectItem implements java.io.Serializable {

	private Integer itemId;
	private int version;
	private TbEmployees tbEmployeesBySigner;
	private TbEmployees tbEmployeesByUpdater;
	private TbEmployees tbEmployeesByCreator;
	private TbProject tbProject;
	private String name;
	private Float hour;
	private String status;
	private Date createdAt;
	private Date updatedAt;
	private Date signedAt;

	public TbProjectItem() {
	}

	public TbProjectItem(TbEmployees tbEmployeesByCreator, TbProject tbProject, String name, String status,
			Date createdAt) {
		this.tbEmployeesByCreator = tbEmployeesByCreator;
		this.tbProject = tbProject;
		this.name = name;
		this.status = status;
		this.createdAt = createdAt;
	}

	public TbProjectItem(TbEmployees tbEmployeesBySigner, TbEmployees tbEmployeesByUpdater,
			TbEmployees tbEmployeesByCreator, TbProject tbProject, String name, Float hour, String status,
			Date createdAt, Date updatedAt, Date signedAt) {
		this.tbEmployeesBySigner = tbEmployeesBySigner;
		this.tbEmployeesByUpdater = tbEmployeesByUpdater;
		this.tbEmployeesByCreator = tbEmployeesByCreator;
		this.tbProject = tbProject;
		this.name = name;
		this.hour = hour;
		this.status = status;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.signedAt = signedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "item_id", unique = true, nullable = false)
	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "signer")
	public TbEmployees getTbEmployeesBySigner() {
		return this.tbEmployeesBySigner;
	}

	public void setTbEmployeesBySigner(TbEmployees tbEmployeesBySigner) {
		this.tbEmployeesBySigner = tbEmployeesBySigner;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "updater")
	public TbEmployees getTbEmployeesByUpdater() {
		return this.tbEmployeesByUpdater;
	}

	public void setTbEmployeesByUpdater(TbEmployees tbEmployeesByUpdater) {
		this.tbEmployeesByUpdater = tbEmployeesByUpdater;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "creator", nullable = false)
	public TbEmployees getTbEmployeesByCreator() {
		return this.tbEmployeesByCreator;
	}

	public void setTbEmployeesByCreator(TbEmployees tbEmployeesByCreator) {
		this.tbEmployeesByCreator = tbEmployeesByCreator;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "project_id", nullable = false)
	public TbProject getTbProject() {
		return this.tbProject;
	}

	public void setTbProject(TbProject tbProject) {
		this.tbProject = tbProject;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "hour")
	public Float getHour() {
		return this.hour;
	}

	public void setHour(Float hour) {
		this.hour = hour;
	}

	@Column(name = "status", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "signed_at", length = 19)
	public Date getSignedAt() {
		return this.signedAt;
	}

	public void setSignedAt(Date signedAt) {
		this.signedAt = signedAt;
	}

}
