package com.yesee.gov.website.model;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbPunchRecords generated by hbm2java
 */
@Entity
@Table(name = "tb_reject_code", catalog = "yesee")
public class TbRejectCode implements java.io.Serializable {

	private Long id;
	private String hashcode;
	private String signer;
	private Integer scheduleId;

	public TbRejectCode() {
	}

	public TbRejectCode(String hashcode, String signer, Integer scheduleId) {
		this.hashcode = hashcode;
		this.signer = signer;
		this.scheduleId = scheduleId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "hashcode", nullable = false, length = 200)
	public String getHashcode() {
		return this.hashcode;
	}

	public void setHashcode(String hashcode) {
		this.hashcode = hashcode;
	}

	@Column(name = "signer", nullable = false, length = 45)
	public String getSigner() {
		return this.signer;
	}

	public void setSigner(String signer) {
		this.signer = signer;
	}

	@Column(name = "schedule_id", nullable = false, length = 11)
	public Integer getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(Integer scheduleId) {
		this.scheduleId = scheduleId;
	}

}
