package com.yesee.gov.website.model;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbSchedules generated by hbm2java
 */
@Entity
@Table(name = "tb_schedules", catalog = "yesee")
public class TbSchedules implements java.io.Serializable {

	private Integer id;
	private TbEmployees tbEmployeesByUser;
	private TbEmployees tbEmployeesByDeputy;
	private TbEmployees tbEmployeesBySigner;
	private int type;
	private Date startTime;
	private Date endTime;
	private String note;
	private Date updatedAt;
	private String updateUser;
	private Date createdAt;
	private String status;
	private Date signedAt;
	private Float annualLeaveTimes;
	private String formNo;
	private Integer originId;


	public TbSchedules() {
	}

	public TbSchedules(TbEmployees tbEmployeesByUser, int type, Date startTime, Date endTime) {
		this.tbEmployeesByUser = tbEmployeesByUser;
		this.type = type;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	public TbSchedules(TbEmployees tbEmployeesByUser, TbEmployees tbEmployeesByDeputy, TbEmployees tbEmployeesBySigner,
			int type, Date startTime, Date endTime, String note, Date updatedAt, String updateUser, Date createdAt,
			String status, Date signedAt, Float annualLeaveTimes, String formNo, Integer originId) {
		this.tbEmployeesByUser = tbEmployeesByUser;
		this.tbEmployeesByDeputy = tbEmployeesByDeputy;
		this.tbEmployeesBySigner = tbEmployeesBySigner;
		this.type = type;
		this.startTime = startTime;
		this.endTime = endTime;
		this.note = note;
		this.updatedAt = updatedAt;
		this.updateUser = updateUser;
		this.createdAt = createdAt;
		this.status = status;
		this.signedAt = signedAt;
		this.annualLeaveTimes = annualLeaveTimes;
		this.formNo = formNo;
		this.originId = originId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user", nullable = false)
	public TbEmployees getTbEmployeesByUser() {
		return this.tbEmployeesByUser;
	}

	public void setTbEmployeesByUser(TbEmployees tbEmployeesByUser) {
		this.tbEmployeesByUser = tbEmployeesByUser;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "deputy")
	public TbEmployees getTbEmployeesByDeputy() {
		return this.tbEmployeesByDeputy;
	}

	public void setTbEmployeesByDeputy(TbEmployees tbEmployeesByDeputy) {
		this.tbEmployeesByDeputy = tbEmployeesByDeputy;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "signer")
	public TbEmployees getTbEmployeesBySigner() {
		return this.tbEmployeesBySigner;
	}

	public void setTbEmployeesBySigner(TbEmployees tbEmployeesBySigner) {
		this.tbEmployeesBySigner = tbEmployeesBySigner;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_time", nullable = false, length = 19)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_time", nullable = false, length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "note", length = 200)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "update_user", length = 45)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "status", length = 20)	
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "signed_at", length = 19)
	public Date getSignedAt() {
		return this.signedAt;
	}

	public void setSignedAt(Date signedAt) {
		this.signedAt = signedAt;
	}

	@Column(name = "annualLeaveTimes", precision = 8, scale = 4)
	public Float getAnnualLeaveTimes() {
		return this.annualLeaveTimes;
	}

	public void setAnnualLeaveTimes(Float annualLeaveTimes) {
		this.annualLeaveTimes = annualLeaveTimes;
	}

	@Column(name = "form_no", length = 20)
	public String getFormNo() {
		return this.formNo;
	}

	public void setFormNo(String formNo) {
		this.formNo = formNo;
	}
	@Column(name = "origin_id")
	public Integer getOriginId() {
		return this.originId;
	}

	public void setOriginId(Integer originId) {
		this.originId = originId;
	}
	
	public String returnTypeString() throws Exception {

		String typeS = "";

		/* ! type 1 2出差 3特休 4事假 5病假 6公假 7婚假 8喪假 9加班 */
		switch (this.type) {
		case 1:
			typeS = "";
			break;
		case 2:
			typeS = "出差";
			break;
		case 3:
			typeS = "特休";
			break;
		case 4:
			typeS = "事假";
			break;
		case 5:
			typeS = "病假";
			break;
		case 6:
			typeS = "公假";
			break;
		case 7:
			typeS = "婚假";
			break;
		case 8:
			typeS = "喪假";
			break;
		case 9:
			typeS = "加班";
			break;
		case 10:
			typeS = "補休";
			break;
		case 11:
			typeS = "外出";
			break;
		}
		return typeS;
	}

}