package com.yesee.gov.website.model;
//default package

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbEmployees generated by hbm2java
 */
@Embeddable
public class TbScheduledLeaveId implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -805145754759654473L;
	private String empName;
	private String skdDate;

	public TbScheduledLeaveId() {
		super();
	}

	public TbScheduledLeaveId(String empName, String skdDate) {
		super();
		this.empName = empName;
		this.skdDate = skdDate;
	}

	@Column(name = "emp_name", unique = true, nullable = false, length = 100)
	public String getEmpName() {
		return empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	@Column(name = "skd_date", nullable = false, length = 256)
	public String getSkdDate() {
		return skdDate;
	}
	
	public void setSkdDate(String skdDate) {
		this.skdDate = skdDate;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((empName == null) ? 0 : empName.hashCode());
		result = prime * result + ((skdDate == null) ? 0 : skdDate.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TbScheduledLeaveId other = (TbScheduledLeaveId) obj;
		if (empName == null) {
			if (other.empName != null)
				return false;
		} else if (!empName.equals(other.empName))
			return false;
		if (skdDate == null) {
			if (other.skdDate != null)
				return false;
		} else if (!skdDate.equals(other.skdDate))
			return false;
		return true;
	}

}
