package com.yesee.gov.website.model;
// default package
// Generated 2019/4/10 �W�� 11:33:19 by Hibernate Tools 4.3.5.Final
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * TbWorkItem generated by hbm2java
 */
@Entity
@Table(name = "tb_work_item", catalog = "yesee")
public class TbWorkItem implements java.io.Serializable {
	private Integer id;
	private TbEmployees tbEmployees;
	private TbProjectItem tbProjectItem;
	private TbProjectItemSort tbProjectItemSort;
	private int proId;
	private String status;
	private float workHr;
	private Date date;
	private String note;
	private Date createdAt;
	private Date updatedAt;
	public TbWorkItem() {
	}
	public TbWorkItem(TbEmployees tbEmployees, int proId, String status, float workHr, Date date, Date createdAt) {
		this.tbEmployees = tbEmployees;
		this.proId = proId;
		this.status = status;
		this.workHr = workHr;
		this.date = date;
		this.createdAt = createdAt;
	}
	public TbWorkItem(TbEmployees tbEmployees, TbProjectItem tbProjectItem, TbProjectItemSort tbProjectItemSort,
			int proId, String status, float workHr, Date date, String note, Date createdAt, Date updatedAt) {
		this.tbEmployees = tbEmployees;
		this.tbProjectItem = tbProjectItem;
		this.tbProjectItemSort = tbProjectItemSort;
		this.proId = proId;
		this.status = status;
		this.workHr = workHr;
		this.date = date;
		this.note = note;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "emp_name", nullable = false)
	public TbEmployees getTbEmployees() {
		return this.tbEmployees;
	}
	public void setTbEmployees(TbEmployees tbEmployees) {
		this.tbEmployees = tbEmployees;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "item_id")
	public TbProjectItem getTbProjectItem() {
		return this.tbProjectItem;
	}
	public void setTbProjectItem(TbProjectItem tbProjectItem) {
		this.tbProjectItem = tbProjectItem;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "sort_id")
	public TbProjectItemSort getTbProjectItemSort() {
		return this.tbProjectItemSort;
	}
	public void setTbProjectItemSort(TbProjectItemSort tbProjectItemSort) {
		this.tbProjectItemSort = tbProjectItemSort;
	}
	@Column(name = "pro_id", nullable = false)
	public int getProId() {
		return this.proId;
	}
	public void setProId(int proId) {
		this.proId = proId;
	}
	@Column(name = "status", nullable = false, length = 9)
	public String getStatus() {
		return this.status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	@Column(name = "work_hr", nullable = false, precision = 12, scale = 0)
	public float getWorkHr() {
		return this.workHr;
	}
	public void setWorkHr(float workHr) {
		this.workHr = workHr;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}
	public void setDate(Date date) {
		this.date = date;
	}
	@Column(name = "note", length = 256)
	public String getNote() {
		return this.note;
	}
	public void setNote(String note) {
		this.note = note;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}