package com.yesee.gov.website.model.accounting;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbGroupFunction generated by hbm2java
 */
@Entity
@Table(name = "tb_a_class_item", catalog = "yesee")
public class TbAClassItem implements java.io.Serializable {

	@Id
	@Column(name = "i_id", unique = true, nullable = false, length = 4)
	private String iId;

	@Column(name = "i_name", nullable = false, length = 10)
	private String iName;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_id", nullable = false, insertable = true, updatable = true)
	private TbAccountingClass cId;

	@Column(name = "directions", length = 20)
	private String directions;

	@Column(name = "enable", nullable = false, length = 10)
	private String enable;

	@Column(name = "create_user", nullable = false, length = 25)
	private String createUser;

	@Column(name = "create_date", nullable = false)
	private Date createDate;

	public TbAClassItem() {
	}

	public TbAClassItem(String iId, String iName, TbAccountingClass cId, String directions, String enable,
			String createUser, Date createDate) {
		this.iId = iId;
		this.iName = iName;
		this.cId = cId;
		this.directions = directions;
		this.enable = enable;
		this.createUser = createUser;
		this.createDate = createDate;

	}

	public String getiId() {
		return iId;
	}

	public void setiId(String iId) {
		this.iId = iId;
	}

	public String getiName() {
		return iName;
	}

	public void setiName(String iName) {
		this.iName = iName;
	}

	public TbAccountingClass getcId() {
		return this.cId;
	}

	public void setcId(TbAccountingClass tbAccountingClass) {
		this.cId = tbAccountingClass;
	}

	public String getDirections() {
		return directions;
	}

	public void setDirections(String directions) {
		this.directions = directions;
	}

	public String getEnable() {
		return enable;
	}

	public void setEnable(String enable) {
		this.enable = enable;
	}

	public String getCreateUser() {
		return createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
