package com.yesee.gov.website.model.accounting;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * TbSignCommon generated by hbm2java
 */
@Entity
@Table(name = "tb_sign_common", catalog = "yesee")
public class TbSignCommon implements java.io.Serializable {

	@Id
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")
	@Column(name = "sign_no", unique = true, nullable = false)
	private String signNo;

	@Column(name = "sign_name", unique = true, nullable = false, length = 15)
	private String signName;

	@Column(name = "create_user",length = 25)
	private String createUser;

	@Column(name = "create_date",length = 10)
	private Date createDate;

	public TbSignCommon() {
	}

	public TbSignCommon(String signNo, String signName, String signUser, String createUser, Date createDate) {
		super();
		this.signNo = signNo;
		this.signName = signName;
		this.createUser = createUser;
		this.createDate = createDate;
	}
	
	

	public TbSignCommon(String signName, String createUser, Date createDate) {
		super();
		this.signName = signName;
		this.createUser = createUser;
		this.createDate = createDate;
	}

	public String getSignNo() {
		return signNo;
	}

	public void setSignNo(String signNo) {
		this.signNo = signNo;
	}

	public String getSignName() {
		return signName;
	}

	public void setSignName(String signName) {
		this.signName = signName;
	}

	public String getCreateUser() {
		return createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
