package employeeSystem.com.website.accounting.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import employeeSystem.com.website.system.model.TbGroup;

/**
 * TbSignRole generated by hbm2java
 */
@Entity
@Table(name = "tb_sign_role", catalog = "yesee")
public class TbSignRole implements java.io.Serializable {

	@Id
	@Column(name = "role_id", unique = true, nullable = false, length = 2)
	private String roleId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role", referencedColumnName = "name", nullable = false, insertable = true, updatable = true)
	private TbGroup role;

	@Column(name = "create_user", nullable = false, length = 25)
	private String createUser;

	@Column(name = "create_date", nullable = false, length = 10)
	private Date createDate;

	public TbSignRole() {

	}

	public TbSignRole(String roleId, TbGroup role, String createUser, Date createDate) {
		super();
		this.roleId = roleId;
		this.role = role;
		this.createUser = createUser;
		this.createDate = createDate;
	}

	public String getRoleId() {
		return roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public TbGroup getRole() {
		return role;
	}

	public void setRole(TbGroup tbGroup) {
		this.role = tbGroup;
	}

	public String getCreateUser() {
		return createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
