package employeeSystem.com.website.accounting.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbVoucherDetail generated by hbm2java
 */
@Entity
@Table(name = "tb_voucher_detail", catalog = "yesee")
public class TbVoucherDetail implements java.io.Serializable {

	@Id
	@Column(name = "detail_no", unique = true, nullable = false, length = 11)
	private String detailNo;

	@Id
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "voucher_no", nullable = false, insertable = true, updatable = true)
	private TbVoucherHead voucherNo;

	@Column(name = "project_id", length = 11)
	private String projectId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "detail_item", nullable = false, insertable = true, updatable = true)
	private TbAClassItem detailItem;

	@Column(name = "amount", nullable = false)
	private Integer amount;

	@Column(name = "directions", length = 200)
	private String directions;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hedge_no", nullable = false, insertable = true, updatable = true)
	private TbHedge hedgeNo;

	@Column(name = "create_user", nullable = false, length = 25)
	private String createUser;

	@Column(name = "create_date", nullable = false)
	private Date createDate;

	@Column(name = "modi_user", length = 10)
	private String modiUser;

	@Column(name = "modi_date")
	private Date modiDate;

	@Column(name = "is_del", nullable = false)
	private String isDel;

	public TbVoucherDetail() {
	}

	public TbVoucherDetail(String detailNo, TbVoucherHead voucherNo, String projectId, TbAClassItem detailItem,
			Integer amount, String directions, TbHedge hedgeNo, String createUser, Date createDate, String isDel) {
		super();
		this.detailNo = detailNo;
		this.voucherNo = voucherNo;
		this.projectId = projectId;
		this.detailItem = detailItem;
		this.amount = amount;
		this.directions = directions;
		this.hedgeNo = hedgeNo;
		this.createUser = createUser;
		this.createDate = createDate;
		this.isDel = isDel;
	}

	public TbVoucherDetail(String detailNo, TbVoucherHead voucherNo, String projectId, TbAClassItem detailItem,
			Integer amount, String directions, TbHedge hedgeNo, String createUser, Date createDate, String modiUser,
			Date modiDate, String isDel) {
		super();
		this.detailNo = detailNo;
		this.voucherNo = voucherNo;
		this.projectId = projectId;
		this.detailItem = detailItem;
		this.amount = amount;
		this.directions = directions;
		this.hedgeNo = hedgeNo;
		this.createUser = createUser;
		this.createDate = createDate;
		this.modiUser = modiUser;
		this.modiDate = modiDate;
		this.isDel = isDel;
	}

	public String getDetailNo() {
		return detailNo;
	}

	public void setDetailNo(String detailNo) {
		this.detailNo = detailNo;
	}

	public TbVoucherHead getVoucherNo() {
		return voucherNo;
	}

	public void setVoucherNo(TbVoucherHead tbVoucherHead) {
		this.voucherNo = tbVoucherHead;
	}

	public String getProjectId() {
		return projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}
	/*
	 * @Column(name = "funds", nullable = false, length = 4) public TbAClassItem
	 * getFunds() { return funds; }
	 */

	public TbAClassItem getDetailItem() {
		return detailItem;
	}

	public void setDetailItem(TbAClassItem tbAClassItem) {
		this.detailItem = tbAClassItem;
	}

	public Integer getAmount() {
		return amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	/*
	 * public String getProperty() { return property; }
	 * 
	 * public void setProperty(String property) { this.property = property; }
	 */

	public String getDirections() {
		return directions;
	}

	public void setDirections(String directions) {
		this.directions = directions;
	}

	public TbHedge getHedgeNo() {
		return hedgeNo;
	}

	public void setHedgeNo(TbHedge tbHedge) {
		this.hedgeNo = tbHedge;
	}

	public String getCreateUser() {
		return createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getModiUser() {
		return modiUser;
	}

	public void setModiUser(String modiUser) {
		this.modiUser = modiUser;
	}

	public Date getModiDate() {
		return modiDate;
	}

	public void setModiDate(Date modiDate) {
		this.modiDate = modiDate;
	}

	public String getIsDel() {
		return isDel;
	}

	public void setIsDel(String isDel) {
		this.isDel = isDel;
	}

}
