package employeeSystem.com.website.accounting.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import employeeSystem.com.website.system.model.TbCompany;

/**
 * TbCustomer generated by hbm2java
 */
@Entity
@Table(name = "tb_voucher_head", catalog = "yesee")
public class TbVoucherHead implements java.io.Serializable {

	@Id
	@Column(name = "voucher_no", unique = true, nullable = false, length = 11)
	private String voucherNo;

	@Column(name = "voucher_name", nullable = false, length = 10)
	private String voucherName;
//	cascade=CascadeType.ALL
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company", referencedColumnName = "name", nullable = false, unique = true, insertable = true, updatable = true)
	private TbCompany company;

	@Column(name = "customer", nullable = true, insertable = true, updatable = true)
	private String customer;

	@Column(name = "cus_tax_id", length = 8)
	private String cusTaxId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "head_item", referencedColumnName = "i_id", nullable = false, insertable = true, updatable = true)
	private TbAClassItem headItem;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hedge_no", nullable = false, insertable = true, updatable = true)
	private TbHedge hedgeNo;

	@Column(name = "amount_total", nullable = false)
	private int amountTotal;

	@Column(name = "applicant", nullable = false, length = 10)
	private String applicant;

	@Column(name = "status", nullable = false, length = 1)
	private String status;

	@Column(name = "credit_date", length = 10)
	private String creditDate;

	@Column(name = "predict_date", length = 10)
	private String predictDate;

	@Column(name = "directions", length = 200)
	private String directions;

	@Column(name = "create_user", nullable = false, length = 20)
	private String createUser;

	@Column(name = "create_date", nullable = false)
	private Date createDate;

	@Column(name = "modi_user", length = 10)
	private String modiUser;

	@Column(name = "modi_date")
	private Date modiDate;

	public TbVoucherHead() {
	}

	public TbVoucherHead(String voucherNo, String voucherName, TbCompany company, String customer, String cusTaxId,
			TbAClassItem headItem, TbHedge hedgeNo, Integer amountTotal, String applicant, String status,
			String creditDate, String predictDate, String directions, String createUser, Date createDate) {
		super();
		this.voucherNo = voucherNo;
		this.voucherName = voucherName;
		this.company = company;
		this.customer = customer;
		this.cusTaxId = cusTaxId;
		this.headItem = headItem;
		this.hedgeNo = hedgeNo;
		this.amountTotal = amountTotal;
		this.applicant = applicant;
		this.status = status;
		this.creditDate = creditDate;
		this.predictDate = predictDate;
		this.directions = directions;
		this.createUser = createUser;
		this.createDate = createDate;
	}

	public TbVoucherHead(String voucherNo, String voucherName, TbCompany company, String customer, String cusTaxId,
			TbAClassItem headItem, TbHedge hedgeNo, int amountTotal, String applicant, String status, String creditDate,
			String predictDate, String directions, String createUser, Date createDate, String modiUser, Date modiDate) {
		super();
		this.voucherNo = voucherNo;
		this.voucherName = voucherName;
		this.company = company;
		this.customer = customer;
		this.cusTaxId = cusTaxId;
		this.headItem = headItem;
		this.hedgeNo = hedgeNo;
		this.amountTotal = amountTotal;
		this.applicant = applicant;
		this.status = status;
		this.creditDate = creditDate;
		this.predictDate = predictDate;
		this.directions = directions;
		this.createUser = createUser;
		this.createDate = createDate;
		this.modiUser = modiUser;
		this.modiDate = modiDate;
	}

	public String getVoucherNo() {
		return voucherNo;
	}

	public void setVoucherNo(String voucherNo) {
		this.voucherNo = voucherNo;
	}

	public String getVoucherName() {
		return voucherName;
	}

	public void setVoucherName(String voucherName) {
		this.voucherName = voucherName;
	}

	public TbCompany getCompany() {
		return company;
	}

	public void setCompany(TbCompany tbcompany) {
		this.company = tbcompany;
	}

	public String getCustomer() {
		return customer;
	}

	public void setCustomer(String customer) {
		this.customer = customer;
	}

	public String getCusTaxId() {
		return cusTaxId;
	}

	public void setCusTaxId(String cusTaxId) {
		this.cusTaxId = cusTaxId;
	}

	public TbAClassItem getHeadItem() {
		return headItem;
	}

	public void setHeadItem(TbAClassItem tbAClassItem) {
		this.headItem = tbAClassItem;
	}

	public TbHedge getHedgeNo() {
		return hedgeNo;
	}

	public void setHedgeNo(TbHedge tbHedge) {
		this.hedgeNo = tbHedge;
	}

	public int getAmountTotal() {
		return amountTotal;
	}

	public void setAmountTotal(int amountTotal) {
		this.amountTotal = amountTotal;
	}

	public String getApplicant() {
		return applicant;
	}

	public void setApplicant(String applicant) {
		this.applicant = applicant;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getCreditDate() {
		return creditDate;
	}

	public void setCreditDate(String currentTimestamp) {
		this.creditDate = currentTimestamp;
	}

	public String getPredictDate() {
		return predictDate;
	}

	public void setPredictDate(String predictDate) {
		this.predictDate = predictDate;
	}

	public String getDirections() {
		return directions;
	}

	public void setDirections(String directions) {
		this.directions = directions;
	}

	public String getCreateUser() {
		return createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getModiUser() {
		return modiUser;
	}

	public void setModiUser(String modiUser) {
		this.modiUser = modiUser;
	}

	public Date getModiDate() {
		return modiDate;
	}

	public void setModiDate(Date modiDate) {
		this.modiDate = modiDate;
	}

}
