package com.yesee.gov.website.model.accounting;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbVoucherHedge generated by hbm2java
 */
@Entity
@Table(name = "tb_voucher_hedge", catalog = "yesee")
public class TbVoucherHedge implements java.io.Serializable {

	@Id
//	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id_SEQ") // 參照下面@GenericGenerator的name
//	@SequenceGenerator(name = "id_SEQ", sequenceName = "tb_voucher_hedge_id", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	private Integer id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hedge_no", nullable = false, insertable = true, updatable = true)
	private TbHedge hedgeNo;

	@Column(name = "h_voucher_no", nullable = false, length = 12)
	private String hVoucherNo;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hedge_item", nullable = false, insertable = true, updatable = true)
	private TbAClassItem hedgeItem;

	@Column(name = "amount", nullable = false)
	private Integer amount;

	@Column(name = "directions", length = 20)
	private String directions;

	@Column(name = "credit_date", nullable = false)
	private String creditDate;

	@Column(name = "exp_status", nullable = false, length = 1)
	private String expStatus;

	@Column(name = "exp_date")
	private Date expDate;

	@Column(name = "create_user", nullable = false, length = 25)
	private String createUser;

	@Column(name = "create_date", nullable = false)
	private Date createDate;

	@Column(name = "modi_user", length = 20)
	private String modiUser;

	@Column(name = "modi_date")
	private Date modiDate;

	public TbVoucherHedge() {
	}

	public TbVoucherHedge(Integer id, TbHedge hedgeNo, String hVoucherNo, TbAClassItem hedgeItem, Integer amount,
			String directions, String creditDate, String expStatus, Date expDate, String createUser, Date createDate,
			String modiUser, Date modiDate) {
		this.id = id;
		this.hedgeNo = hedgeNo;
		this.hVoucherNo = hVoucherNo;
		this.hedgeItem = hedgeItem;
		this.amount = amount;
		this.directions = directions;
		this.creditDate = creditDate;
		this.expStatus = expStatus;
		this.expDate = expDate;
		this.createUser = createUser;
		this.createDate = createDate;
		this.modiUser = modiUser;
		this.modiDate = modiDate;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TbHedge getHedgeNo() {
		return hedgeNo;
	}

	public void setHedgeNo(TbHedge tbHedge) {
		this.hedgeNo = tbHedge;
	}

	public String gethVoucherNo() {
		return hVoucherNo;
	}

	public void sethVoucherNo(String hVoucherNo) {
		this.hVoucherNo = hVoucherNo;
	}

	public TbAClassItem getHedgeItem() {
		return hedgeItem;
	}

	public void setHedgeItem(TbAClassItem tbAClassItem) {
		this.hedgeItem = tbAClassItem;
	}

	public Integer getAmount() {
		return amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	public String getDirections() {
		return directions;
	}

	public void setDirections(String directions) {
		this.directions = directions;
	}

	public String getCreditDate() {
		return creditDate;
	}

	public void setCreditDate(String creditDate) {
		this.creditDate = creditDate;
	}

	public String getExpStatus() {
		return expStatus;
	}

	public void setExpStatus(String expStatus) {
		this.expStatus = expStatus;
	}

	public Date getExpDate() {
		return expDate;
	}

	public void setExpDate(Date expDate) {
		this.expDate = expDate;
	}

	public String getCreateUser() {
		return createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getModiUser() {
		return modiUser;
	}

	public void setModiUser(String modiUser) {
		this.modiUser = modiUser;
	}

	public Date getModiDate() {
		return modiDate;
	}

	public void setModiDate(Date modiDate) {
		this.modiDate = modiDate;
	}
}
