package com.yesee.gov.website.model.accounting;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbVoucherHistory generated by hbm2java
 */
@Entity
@Table(name = "tb_voucher_history", catalog = "yesee")
public class TbVoucherHistory implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "serial", unique = true, nullable = false, length = 15)
	private Integer serial;

	@Column(name = "voucher_no", nullable = false, length = 15)
	private String voucherNo;

	@Column(name = "i_id", nullable = false, length = 4)
	private String iId;

	@Column(name = "i_name", nullable = false, length = 10)
	private String iName;

	@Column(name = "amount", nullable = false)
	private Integer amount;

	@Column(name = "io_type", nullable = false, length = 1)
	private String ioType;

	@Column(name = "applicant", nullable = false, length = 10)
	private String applicant;

	@Column(name = "sign_user", nullable = false, length = 25)
	private String signUser;

	@Column(name = "directions", length = 200)
	private String directions;

	@Column(name = "status", nullable = false, length = 1)
	private String status;

	@Column(name = "create_user", nullable = false, length = 25)
	private String createUser;

	@Column(name = "create_date", nullable = false)
	private Date createDate;

	@Column(name = "modi_user", nullable = false, length = 25)
	private String modiUser;

	@Column(name = "modi_date", nullable = false)
	private String modiDate;

	public TbVoucherHistory() {
	}

	public TbVoucherHistory(Integer serial, String voucherNo, String iId, String iName, Integer amount, String ioType,
			String applicant, String signUser, String directions, String status, String createUser, Date createDate,
			String modiUser, String modiDate) {

		this.serial = serial;
		this.voucherNo = voucherNo;
		this.iId = iId;
		this.iName = iName;
		this.amount = amount;
		this.ioType = ioType;
		this.applicant = applicant;
		this.signUser = signUser;
		this.directions = directions;
		this.status = status;
		this.createUser = createUser;
		this.createDate = createDate;
		this.modiUser = modiUser;
		this.modiDate = modiDate;
	}

	public Integer getSerial() {
		return serial;
	}

	public void setSerial(Integer serial) {
		this.serial = serial;
	}

	public String getVoucherNo() {
		return voucherNo;
	}

	public void setVoucherNo(String voucherNo) {
		this.voucherNo = voucherNo;
	}

	public String getiId() {
		return iId;
	}

	public void setiId(String iId) {
		this.iId = iId;
	}

	public String getiName() {
		return iName;
	}

	public void setiName(String iName) {
		this.iName = iName;
	}

	public Integer getAmount() {
		return amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	public String getIoType() {
		return ioType;
	}

	public void setIoType(String ioType) {
		this.ioType = ioType;
	}

	public String getApplicant() {
		return applicant;
	}

	public void setApplicant(String applicant) {
		this.applicant = applicant;
	}

	public String getSignUser() {
		return signUser;
	}

	public void setSignUser(String signUser) {
		this.signUser = signUser;
	}

	public String getDirections() {
		return directions;
	}

	public void setDirections(String directions) {
		this.directions = directions;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getCreateUser() {
		return createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getModiUser() {
		return modiUser;
	}

	public void setModiUser(String modiUser) {
		this.modiUser = modiUser;
	}

	public String getModiDate() {
		return modiDate;
	}

	public void setModiDate(String modiDate) {
		this.modiDate = modiDate;
	}

}
