package employeeSystem.com.website.accounting.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbCustomer generated by hbm2java
 */
@Entity
@Table(name = "tb_voucher_common", catalog = "yesee")
public class TbVoucherCommon implements java.io.Serializable {

	// Table FK 待確認
	@Id
	@Column(name = "voucher_no", unique = true, nullable = false, insertable = true, updatable = true)
	private String voucherNo;

	@Column(name = "voucher_name", nullable = false, length = 10)
	private String voucherName;

	@Column(name = "create_user", nullable = false, length = 20)
	private String createUser;

	@Column(name = "create_date", nullable = false)
	private Date createDate;

	public TbVoucherCommon() {
		super();
	}

	public TbVoucherCommon(String voucherNo, String voucherName, String createUser, Date createDate) {
		super();
		this.voucherNo = voucherNo;
		this.voucherName = voucherName;
		this.createUser = createUser;
		this.createDate = createDate;
	}

	public String getVoucherNo() {
		return voucherNo;
	}

	public void setVoucherNo(String voucherNo) {
		this.voucherNo = voucherNo;
	}

	public String getVoucherName() {
		return voucherName;
	}

	public void setVoucherName(String voucherName) {
		this.voucherName = voucherName;
	}

	public String getCreateUser() {
		return createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
