package com.yesee.gov.website.model.accounting;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * TbVoucherModifyAuth generated by hbm2java
 */
@Entity
@Table(name = "tb_voucher_modify_auth", catalog = "yesee")
public class TbVoucherModifyAuth implements java.io.Serializable {

	@Id
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")
	@Column(name = "token", unique = true, nullable = false, length = 36)
	private String token;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "voucher_no", nullable = false, unique = true, insertable = true, updatable = true)
	private TbVoucherHead voucherNo;

	@Column(name = "create_user", nullable = false, length = 25)
	private String createUser;

	@Column(name = "create_date", nullable = false)
	private Date createDate;

	public TbVoucherModifyAuth() {
	}

	public TbVoucherModifyAuth(String token, TbVoucherHead voucherNo, String createUser, Date createDate) {
		super();
		this.token = token;
		this.voucherNo = voucherNo;
		this.createUser = createUser;
		this.createDate = createDate;
	}

	public TbVoucherModifyAuth(TbVoucherHead voucherNo, String createUser, Date createDate) {
		super();
		this.voucherNo = voucherNo;
		this.createUser = createUser;
		this.createDate = createDate;
	}

	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public TbVoucherHead getVoucherNo() {
		return voucherNo;
	}

	public void setVoucherNo(TbVoucherHead tbVoucherHead) {
		this.voucherNo = tbVoucherHead;
	}

	public String getCreateUser() {
		return createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
